/** \file
 *  This C header file was generated by $ANTLR version 3.5.3
 *
 *     -  From the grammar source file : AwesomeLang.g
 *     -                            On : 2024-10-06 02:39:10
 *     -                 for the lexer : AwesomeLangLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
AwesomeLangLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pAwesomeLangLexer, which is returned from a call to AwesomeLangLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pAwesomeLangLexer are  as follows:
 *
 *  - 
 void
      pAwesomeLangLexer->T__11(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__12(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__13(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__14(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__15(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__16(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__17(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__18(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__19(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__20(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__21(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__22(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__23(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__24(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__25(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__26(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__27(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__28(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__29(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__30(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__31(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__32(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__33(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__34(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__35(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__36(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__37(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__38(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__39(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__40(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__41(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__42(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__43(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__44(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__45(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__46(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__47(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__48(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__49(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__50(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__51(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__52(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__53(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->T__54(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->BOOL(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->IDENTIFIER(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->STRING(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->CHAR(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->HEX(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->BITS(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->DEC(pAwesomeLangLexer)
 *  - 
 void
      pAwesomeLangLexer->Tokens(pAwesomeLangLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_AwesomeLangLexer_H
#define _AwesomeLangLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct AwesomeLangLexer_Ctx_struct AwesomeLangLexer, * pAwesomeLangLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
AwesomeLangLexer

 */
struct AwesomeLangLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__11)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__12)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__13)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__14)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__15)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__16)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__17)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__18)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__19)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__31)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__32)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__33)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__34)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__42)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__43)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__44)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__45)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__46)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__47)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__48)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mBOOL)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mCHAR)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mHEX)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mBITS)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mDEC)	(struct AwesomeLangLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct AwesomeLangLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct AwesomeLangLexer_Ctx_struct * ctx);
    void	    (*free)   (struct AwesomeLangLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pAwesomeLangLexer AwesomeLangLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pAwesomeLangLexer AwesomeLangLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__11      11
#define T__12      12
#define T__13      13
#define T__14      14
#define T__15      15
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define BITS      4
#define BOOL      5
#define CHAR      6
#define DEC      7
#define HEX      8
#define IDENTIFIER      9
#define STRING      10
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for AwesomeLangLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
